name: flutter_auth_app
description: "A new Flutter project."
publish_to: 'none'

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.2
  equatable: ^2.0.7
  lottie: ^3.3.2
  http: ^1.6.0
  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
